### PR TITLE
Add horizontal logo variations

### PR DESCRIPTION
**Pull request by Conan-Kudo**
These were needed for making some remix branding, so these were adapted from the regular "vertical" variant with the word mark.

### CODE REVIEW

**Comment by marcan** [comment]
These should be in the `src` directory; `svg` is for exports with the Inkscape metadata stripped ("plain SVG"). If you run `make` with the files in `src`, it should generate the plain SVG and all the PNG versions for you.

**Comment by soundflora** [comment]
I think that looks good, but maybe with a few tweaks it would look even better!

1. Lower the text a little bit (right now it looks like it's sort of floating relative to the logo mark, visually)
2. Make the text smaller to balance the presence with the logo mark, 96% or so of the current size
3. Maybe add more space between the logo and the text (113 pixels or so)

I've attached an SVG of the general idea, feel free to use it as a reference.
AsahiLinux_logo_horizontal_a

**Comment by Conan-Kudo** [comment]
@marcan @soundflora I think I've addressed your feedback, though the makefile kinda went rampant with creating variations of the file...

**Review by soundflora — APPROVED** [review]
Looks good to me, thank you for the changes!

**Pull request merged**
